name: Vitest Tests

on:
  workflow_call:

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install root dependencies
        run: npm install
      - name: Install test dependencies
        working-directory: ./tests/vitest
        run: npm install
      - name: Run Vitest tests and generate reports
        working-directory: ./tests/vitest
        run: |
          npm run test:reports:cobertura
          npm run test:reports:summary
      - name: Upload JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: tests/vitest/test-results/junit-report.xml
      - name: Upload Cobertura coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-coverage
          path: tests/vitest/coverage/cobertura/
      - name: Test Report
        uses: dorny/test-reporter@v2.1.1
        if : always()
        with:
          name: Vitest Tests
          path: tests/vitest/test-results/junit-report.xml
      - name: Coverage Test Report
        uses: j0hnlam/cobertura-action@v16
        if: always()
        with:
          path: tests/vitest/coverage/cobertura/cobertura-coverage.xml